### ISSUE TITLE
Use mod storage

### ISSUE THREAD

**Issue by tacotexmex** [SmallJoker/simple_protection#16]
Instead of writing to file, [get_mod_storage](http://dev.minetest.net/minetest.get_mod_storage) may be used.

**Comment by SmallJoker** [comment]
The ModStorage is a rather new feature in Minetest. Added in [February 2017](https://github.com/minetest/minetest/commit/ef6feca), i.e. 0.4.16-stable contains it.
As far I can see it's just a plain JSON file with fancy functions around, so no great improvement to the current methods instead of having them as 1 or 2-liners but maybe unreadable when opening the file with an editor. The current functions work nicely but we may need this feature to implement area names.

**Comment by SmallJoker** [comment]
Replaced in favour for #19 (using sqlite). Pros/cons are listed there.
